version: '3.9'
services:
    blending-worker:
        build:
            context: ./be  # This context is done in this way to include the shared_lib in the blending worker dockerfile.
            dockerfile: ./workers/blending/Dockerfile
        depends_on:
            - rabbitmq
        volumes:
            - ./be/workers/blending:/app
            - ./be/shared_lib:/shared_lib
        ports:
            - 5678:5678  # TODO: port for debugging, make this conditional on deployment environment (DEV vs PROD)
    api:
        build:
            context: ./be/api
            target: debug  # Replace this for prod to prod
        ports:
            - "3001:3001"
            - "9229:9229"  # for attaching node debugger
        volumes:
            - ./be/api:/app
            - ./be/workers/blending/data_generator:/app/data
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
    web:
        build: ./fe
        ports:
            - "3000:3000"
        command: npm run start
        volumes:
            - ./fe:/app
    mongo:
        image: mongo
        ports:
            - "27017:27017"
