version: '3.9'
services:
    web:
        build: ./fe
        ports:
            - "3000:3000"
        command: npm run start
        volumes:
            - ./fe:/app
    api:
        build: ./be/api
        ports:
            - "3001:3001"
        command: npm run dev
        volumes:
            - ./be/api:/app
